#:schema node_modules/wrangler/config-schema.json
name = "openai-proxy"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

routes = [
	{ pattern = "openai-proxy.api.submap.com", custom_domain = true }
]